.github/workflows/build.yml, .github/workflows/ci.yml, Cross.toml, pixi.toml
ubuntu-arm runners are not available in public repos
Use cargo-cross to cross-compile for linux-aarch
=> chore: use cross for linux-arm builds

src/unpack.rs
`pixi-pack unpack` does not properly clean up the temporary unpack directory.
Fix resource leak for temporary directory.
=> fix: Fix resource leak for tmp dir during unpack

Cargo.lock, Cargo.toml
The conda-forge builds are failing because `syn 2.0.69` to`2.0.72` lead to a segmentation fault while compiling. Using `syn 2.0.74` should fix the issue.
Thanks @0xbe7a for figuring this out!
=> chore: Bump dependencies

Cargo.lock, Cargo.toml, src/unpack.rs
The rattler package cache temporary directory leaks.
Similar to #42, fix the leaking temporary directory.
=> fix: Fix leaking package cache directory

src/unpack.rs
The unpack command logs "finished" before being finished.
Move finish log to end of unpack function.
=> refactor: Move unpack finished log to end of unpack

examples/auth/pixi.lock, examples/auth/pixi.toml, src/pack.rs, tests/integration_test.rs
Closes #35.
Propagate HTTP error into actual runtime error.
=> fix: Throw error when package download fails

.github/workflows/build.yml, .github/workflows/ci.yml
We don't require the merge queue anymore.
Remove merge queue.
=> ci: Remove merge queue from workflows

Cargo.lock, Cargo.toml, src/pack.rs, src/util.rs, tests/integration_test.rs
Closes #41.
* Update timestamp of conda packages to timestamp from `pixi.lock`
* Update timestamp of other files in archive to UNIX epoch
=> fix: Set timestamps correctly inside pack

README.md, src/unpack.rs
=> chore: Rename local channel to pixi-pack

src/lib.rs, src/main.rs, src/unpack.rs
Would be nice to have some information what was being used to generate the pack file. Is also nice for reproducibility
Write `pixi-pack-version` to `pixi-pack.json`.
If the version differs during unpack, we will print a `WARN` (only gets shown when `pixi-pack unpack -v`).
Make version `Option` to support older versions of pixi-pack.
=> feat: Write pixi-pack-version to metadata file

Cargo.lock, Cargo.toml, examples/no-timestamp/pixi.lock, examples/no-timestamp/pixi.toml, src/pack.rs, tests/integration_test.rs
=> fix: Use default when no timestamp is provided in package

src/main.rs, src/pack.rs, tests/integration_test.rs
Allow `pixi-pack pack <manifest-path>` to accept a path to a project directory. This ports the same feature added to upstream Pixi here https://github.com/prefix-dev/pixi/pull/2716.
This also adds an additional check if the manifest path is invalid and display an error.
Fixes: https://github.com/Quantco/pixi-pack/issues/93
This makes pixi-pack align with how `pixi --manifest-path` works.
This fixes the bug in #93 where if a directory is used for `pixi-pack pack <directory>`, pixi pack doesn't handle it correctly and searches the directory's parent for the pixi.lock
=> feat: Support manifest path to project directory

pixi.toml
```
WARN Encountered ambiguous version specifier `1.81.0`, could be `1.81.0.*` but assuming you meant `==1.81.0`. In the future this will result in an error.
```
=> chore: Fix pixi warning

Cargo.lock, Cargo.toml, src/unpack.rs
There's a bug in the way we convert the filepath to a `file://` URL when installing packages during unpack on Windows.
Properly convert filepaths to URLs.
=> fix: Properly convert filepath to URL during unpacking

Cargo.lock, Cargo.toml, README.md, src/main.rs, src/pack.rs, tests/integration_test.rs
Following up on https://github.com/Quantco/pixi-pack/issues/100 (thanks for the opportunity @pavelzw !).
As the README of this PR states, having a cache for downloads is useful when:
* Creating multiple packs with overlapping dependencies
* Working with large packages that take time to download
* Operating in environments with limited bandwidth
* Running CI/CD pipelines where package caching can significantly improve build times
`pixi`'s cache is for already-extracted packages, but here we need them un-extracted, so implementing an optional (behind the `--use-cache` flag) cache for downloads.
I have little experience in Rust[1], let me know if this is an okay implementation. 
There are some formatting changes, I used the autoformat feature from VSCode with the rust-analyzer extension.
- …
=> feat: Implement a --use-cache flag closes #100

.github/PULL_REQUEST_TEMPLATE.md, README.md
=> docs: Mention add_pip_as_python_dependency in compatibility mode

src/pack.rs, tests/integration_test.rs
Unnecessary error object when checking http response status.
=> refactor: Use error_for_status in response

Cargo.lock, Cargo.toml, src/pack.rs, src/unpack.rs
=> build: Bump rattler dependencies

Cargo.lock, Cargo.toml, src/pack.rs
=> fix: Auth middleware not used in mirrored channels

.github/workflows/build.yml
=> ci: Use windows arm runner during build

.github/workflows/ci.yml, .gitignore, Cargo.lock, Cargo.toml
see https://github.com/prefix-dev/pixi/issues/2839 https://github.com/prefix-dev/pixi/pull/3191
add patch to make sure we don't build version-ranges twice.
---
=> chore: make sure we only build one version of `version-ranges`

.github/workflows/build.yml, .typos.toml, README.md
This adds build provenance based on the official manual of [slsa.dev](https://slsa.dev/) so that people can verify that the archives are produced by us.
You can test it on my fork using:
```
wget https://github.com/xhochy/pixi-pack/releases/download/v0.6.12/multiple.intoto.jsonl
wget https://github.com/xhochy/pixi-pack/releases/download/v0.6.12/pixi-pack-aarch64-apple-darwin
pixi exec slsa-verifier verify-artifact pixi-pack-aarch64-apple-darwin --provenance-path multiple.intoto.jsonl --source-uri github.com/xhochy/pixi-pack --source-branch main
```
As a follow-up, I would also try to integrate https://github.com/actions/attest-build-provenance into this repository. Long-term, it probably makes sense to use only one of them.
Integrated the `slsa-framework/slsa-github-generator` workflow …
=> ci: Generate hashes for SLSA

Cargo.lock, Cargo.toml, src/main.rs
```
❯ cargo run -- pack
Compiling pixi-pack v0.6.3 (/Users/pavel/projects/pixi-pack)
Finished `dev` profile [unoptimized + debuginfo] target(s) in 6.13s
Running `target/debug/pixi-pack pack`
thread 'main' panicked at /Users/pavel/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/clap_builder-4.5.37/src/builder/debug_asserts.rs:112:17:
Command pack: Short option names must be unique for each argument, but '-p' is in use by both 'platform' and 'pixi_pack_source'
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
didn't test #156 enough
---
=> fix: Panic due to duplicate -p handles

.github/workflows/build.yml, README.md
As a comparison to plain SLSA attestations, I have also implemented the GitHub native workflow: https://github.com/xhochy/pixi-pack/attestations/6913616. It looks much simpler, but also adds a bit more vendor-lock-in.
=> ci: Upload artifact attestation on release

.github/workflows/build.yml, .github/workflows/chore.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml
=> ci: Set explict top-level permissions for GHA

CITATION.cff
Closes #199 
Add `CITATION.cff`.
---
=> docs: Add citation.cff file

README.md
Closes #200 
Fix 404 in README.
---
=> fix: Fix 404 in readme
